# Generated by Django 4.1.2 on 2022-11-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0002_rename_edad_familiares_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiares',
            new_name='Persona',
        ),
    ]
