# Generated by Django 4.1.2 on 2022-11-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0003_rename_familiares_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
