# Generated by Django 4.1.2 on 2022-11-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0006_producto_provedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provedor',
            new_name='Proveedor',
        ),
    ]
