# Generated by Django 4.1.2 on 2022-11-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0007_rename_provedor_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=20),
        ),
    ]
